apiVersion: 1

datasources:
  - name: ClickHouse
    uid: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    jsonData:
      defaultDatabase: gallery
      port: 8123
      protocol: http
      server: clickhouse
      username: default
    secureJsonData:
      password: ""
